# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38a639f3920aad1b98a62e96eb0c3ca7c701ba922fe209b69b5bb813533a8a1577e56082140e5a72fd250c509bbb5fa5e7774a23d49779d19ed87654eabb2f73

test:
  secret_key_base: e78a353da9f67330089ae6f941eeb8220a3fa01b9b39641ef7b4a899240859302afc2852d110e8362b39d66976bf29450dfe8461258ca2a6df27c5f6a1055579

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
